[project]
name = "analytical-platform-python-uv-example"
version = "0.1.0"
description = "Analytical Platform Python uv Example"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3==1.37.24",
    "notifications-python-client==10.0.1",
]
