---
name: Dependency Review

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: {}

jobs:
  dependency-review:
    if: github.event.repository.private == false
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-dependency-review.yml@c5e5677a7f4f9f65829996f00106c792610facfa # v1.4.1
