---
name: Release Container

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  release-container:
    permissions:
      contents: read
      id-token: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-release-container.yml@f2a2ea6eca6ce4bdc265dbb56c06a1703c6bd823 # v1.8.0
