---
name: Release Container

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  release-container:
    permissions:
      contents: read
      id-token: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-release-container.yml@c5e5677a7f4f9f65829996f00106c792610facfa # v1.4.1
