---
name: Release Container

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  release-container:
    permissions:
      contents: read
      id-token: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-release-container.yml@39e4c8e5bdde50a537934e2a29d9e3d02b5ca1ce # v2.2.1
