---
name: Scan Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan-container:
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-scan-container.yml@9950dfb8d7f5af5a1b63124cdcae60b10f3a20c5 # v1.10.0
    with:
      runtime: python
