---
name: Scan Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan-container:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-scan-container.yml@2e73d776c52be2e1c787f4771fa8af5384875f7b # v2.5.0
    with:
      runtime: python
