---
name: Scan Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan-container:
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-scan-container.yml@2f3670fbb0b7e2c5fc0fd3ff0c58caa758dd913e # v1.7.0
    with:
      runtime: python
